### ISSUE TITLE
libfclib-dev isn't available in ppa in Ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by pawanw17** [robocomp/dsr-graph#28]
In the installation page, maybe it'll be a good idea to have instructions to install from source.
https://github.com/pawanw17/dsr-graph/blob/development/README.md

will create a PR suggesting the alternate installation if anyone faces issues with ppa installation.

**Comment by pbustos** [comment]
I think there was a similar package because we were using it and I don't think we compiled it from sources in 18.04

**Comment by pawanw17** [comment]
Can I have the name if possible because my build with FCL_SUPPORT is failing on bionic, however it builds fine on 20.04 Focal.

**Comment by orensbruli** [comment]
apt-get install --no-install-recommends --yes libfcl-dev
does it work for you in bionic?
It looks like this is the package in the https://packages.ubuntu.com/bionic/libfcl-dev

**Comment by pawanw17** [comment]
nope, still failing :/

**Comment by orensbruli** [comment]
Oh, ok. I think I know what is the problem.
[libfclib-dev](https://packages.ubuntu.com/search?keywords=libfclib-dev) vs [libfcl-dev](https://packages.ubuntu.com/bionic/libfcl-dev)
I need to do some more testing to see what's really happening.

**Comment by pawanw17** [comment]
I did some testing and found out that libfclib-dev is needed to build... in ubuntu 20.04, but am unable to properly install libfclib-dev on bionic...

**Comment by orensbruli** [comment]
I'm not sure libfclib-dev is really needed in 18 or 20. I think it was a typo. What I really think it's needed is libfcl-dev.
Could you try to uninstall libfclib-dev and install libfcl-dev in your Bionic distribution and tell us if something changes?

**Comment by pawanw17** [comment]
Yes sure!

**Comment by pawanw17** [comment]
Okay so I tried removing libfclib-dev and building again only with libfcl-dev on ubuntu 20.04 but it fails.... However it builds successfully with libfclib-dev ... :/
in ubuntu 18.04 I am unable to build because lack of libfclib-dev in ppa and installing from source isn't helping...

**Comment by pawanw17** [comment]
I have libfcl-dev but the build's still failing with FCL_SUPPORT ...

**Comment by pawanw17** [comment]
Alright so on a fresh install of ubuntu (tested in a vm) I was able to build it successfully with libfcl-dev only :) , I think there might be some issue with my distro, will try to debug it, thanks for correcting the typo!

**Comment by orensbruli** [comment]
Ok! Perfect. Happy to know. Best!
