### ISSUE TITLE
viriato-pyrep doesn't stop with keyboard interrupt

### ISSUE THREAD

**Issue by pawanw17** [robocomp/dsr-graph#31]
The node needs the capabilty to handle keyboard interrupts so processes are safely closed

Distro : Ubuntu 18.04
Files used to run the node : robots_pyrep/viriatoPyrep/run.sh

**Comment by orensbruli** [comment]
Probably fixed in one of these commits:
https://github.com/robocomp/robocomp/commit/7685de5598ede681933f86b489c110766d842714
https://github.com/robocomp/robocomp/commit/803c2a67fb0b5a7f7a3af7cbc03549a8fbfc3b8c
https://github.com/robocomp/robocomp/commit/e3c97f27851e45a20a7cf450342cd9df66a54570
